
[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200

monitor_filters = esp32_exception_decoder, direct, send_on_enter, time  ;, log2file

build_flags =
        -D CORE_DEBUG_LEVEL=4
        -D CONFIG_ARDUHAL_LOG_COLORS
  ;-D CORE2_AVI_AUDIO_MASTER
  ;-D ARDUINO_USB_CDC_ON_BOOT=0
  -D AUDIO_SR=48000
  -D AUDIO_BITS=16
  -D AUDIO_CHANNELS=1
lib_deps =
  m5stack/M5GFX
  https://github.com/m5stack/M5Core2.git

