
[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200
build_flags =
  -D CORE2_AVI_AUDIO_MASTER
  -D ARDUINO_USB_CDC_ON_BOOT=0
  -D AUDIO_SR=44100
  -D AUDIO_BITS=16
  -D AUDIO_CHANNELS=1
lib_deps =
  SD
  SPI
  m5stack/M5GFX
  https://github.com/m5stack/M5Core2.git
  https://github.com/lanyou1900/avilib.git

; 本プロジェクトは M5Unified を使用しません。
; SD アクセスは Arduino の SD.h を使用し、/sdcard に自動マウントされることを前提にしています。
